baseURL = "https://syyim.netlify.app"
title = "syyim"
theme = "anubis"
paginate = 5
summaryLength = 30
disqusShortname = ""
googleAnalytics = "UA-167094170-1"
enableRobotsTXT = true

[author]
name = "lovejaco@gmail.com"

[params]
author = "sungyeol.yim"
description = "syyim blog"

[menu]

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 1

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 2

[[menu.main]]
name = "Archive"
identifier = "archive"
url = "/posts/"
weight = 3

[[menu.main]]
identifier = "contact"
name = "Contact"
url = "/contact/"
weight = 4
